Update Nix inputs (nix flake update)
Something is wrong with the `self.submodules = true` behaviour here,
leading to this error:

```
error: opening file '/nix/store/pxbs1v6i8f6vwai2vgkwcdlcpxmk515c-source/semcode/Cargo.toml': No such file or directory
```

The whole semcode/ directory in the src derivation is empty. I don't
understand this.

Updating the inputs fixes it (the source derivation output becomes
properly populated). I don't understand why. Since it's likely pretty
few people use this anyway, I propose to just merge this and see if the
problem ever recurs.